Rails.application.config.assets.precompile += %w( pleasy.css )
Rails.application.config.assets.precompile += %w( init.js )
Rails.application.config.assets.precompile += %w( skel.min.js )
Rails.application.config.assets.precompile += %w( login.css )

Rails.application.config.assets.precompile += %w( demo.css )
Rails.application.config.assets.precompile += %w( font-awesome.css )
Rails.application.config.assets.precompile += %w( menu_topside.css )
Rails.application.config.assets.precompile += %w( normalize.css )
Rails.application.config.assets.precompile += %w( scaffolds.css )
Rails.application.config.assets.precompile += %w( metro-bootstrap.css )